### ISSUE TITLE
RGP crashes every 32-bit Vulkan app

### ISSUE THREAD

**Issue by miller36** [GPUOpen-Tools/Radeon-GPUProfiler#10]
Specifically, it crashes amdvlk32.dll preventing you from profiling them. 64-bit Vulkan apps work fine.

Hardware/software used:
Graphics card: Radeon RX 560 (MSI Aero 4GB)
Driver version: Adrenalin 18.3.1
Windows: 7 64-bit
RGP version: 1.11.17

How to reproduce:
1) open RadeonDeveloperPanel.exe and click Connect
2) add any 32-bit Vulkan app executable to a target app list (VULKAN_SDK\bin32\cube.exe is a good example)
3) run the app

If you need more info, please let me know.

**Comment by ahosier** [comment]
Hi,

Thank you for the feedback. I've confirmed what you're seeing and passed on the details of the crash to the parties involved and they'll will be working on a fix.

Thanks,
Tony.

**Comment by ahosier** [comment]
Hi,

Just to let you know that this issue has been fixed in the latest AMD driver.

Thanks,
Tony.
