### ISSUE TITLE
AMD APU + AMD GPU combinations supported? 

### ISSUE THREAD

**Issue by codedivine** [GPUOpen-Tools/Radeon-GPUProfiler#11]
I am looking at some laptop configurations with AMD APU (either the older Bristol Ridge or the newer Raven Ridge) with a discrete RX 500 series GPUs.  Are these combinations supported?  Will I able to use the Radeon GPU profiler to profile the discrete GPU?

**Comment by bpurnomo** [comment]
Hi,
RGP supports the following discrete GPUs:
- AMD RX Vega 64 and RX Vega 56
- AMD Radeon™ R9 Fury and Nano series
- AMD Radeon™ RX 400 and RX 500 series
- AMD Tonga R9 285, R9 380

It can be in a laptop configuration with an AMD or Intel APU.
