### ISSUE TITLE
Radeon-GPUProfiler 1.2 announced at GDC last week coming soon?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Tools/Radeon-GPUProfiler#12]

**Comment by gselley** [comment]
Yes, coming soon. ETA mid-April.

**Comment by pszi1ard** [comment]
I guess you meant GDC not GTC (the latter is NVIDIA's conference :)).

**Comment by oscarbg** [comment]
it's a typo yes..

**Comment by oscarbg** [comment]
@gselley no pressure but any update? Coming this month?

**Comment by ahosier** [comment]
Hi Oscarbg,

RGP V1.2 has just gone live. This version contains the RGP/RenderDoc interop functionality demonstrated at GDC.
