### ISSUE TITLE
Cryptic Error Message In Developer Panel

### ISSUE THREAD

**Issue by romanlarionov** [GPUOpen-Tools/Radeon-GPUProfiler#14]
I'm trying to capture a trace for a simple Vulkan app that only uses compute. The app only sets up the vulkan state, issues a direct dispatch call (through a compute queue), and submits the queue and waits until completion. I have no error/warning messages popping up from the LunarG validation layers.

It's a pretty straightforward app with the exception that I do not have a main render loop, nor do I present anything via vkQueuePresentKHR().

I get a cryptic error message when trying to capture a trace:
```
[RDP] Received client connected from unknown client with id 1888.
[RDP] Received client halted from unknown client with id 1888.
[RDP] Processing halted client with id 1888: VulkanThreadScheduler.exe:19844 - AMD Vulkan Driver
[RDP] Updated VulkanThreadScheduler.exe ClientId to 1888
[RDP] Connected DriverControlClient to process 'VulkanThreadScheduler.exe', ProcessId = 19844
[RDP] Filtered halted process with ProcessId = 19844
[RDP] Enabled profiling for target executable 'VulkanThreadScheduler.exe', ProcessId = 19844.
[RDP] Set profiling flag for ProcessId = 19844 to true.
[RDP] Capture profile button is enabled because the target application is profilable and there is no profile in progress.
[RDP] Found 0 settings.
[RDP] Resumed execution of process 'VulkanThreadScheduler.exe', ProcessId = 19844. Disconnect client.
[RDP] Driver has been initialized within VulkanThreadScheduler.exe process. Attempting to retrieve device clock frequencies.
[RDP] Successfully queried maximum device clocks.
[RDP] Successfully set device clock mode to Normal to query frequency.
[RDP] Successfully queried device clock frequencies for Normal mode.
[RDP] Successfully set device clock mode to Stable to query frequency.
[RDP] Successfully queried device clock frequencies for Stable mode.
[RDP] Successfully collected device clock frequencies.
[RDP] Reverting to user's clock mode.
[RDP] Set clock mode to Normal.
[RDP] Driver initialized successfully on target client VulkanThreadScheduler.exe.
[RDP] Capture profile button has been disabled because there is an active profile in progress.
[RDP] Set clock mode to Peak for profiling.
[RDP] Profiling began successfully.
[RDP] Reverted clock after profiling to Normal.
[RDP] Failed to finish executing profile with code 'Error'.
[RDP] Capture profile button is enabled because the target application is profilable and there is no profile in progress.
[RDP] Client with Id 1888 has disconnected.
[RDP] Capture profile button has been disabled because the application is not profilable.
```

I assume this line signifies something's wrong: ` [RDP] Failed to finish executing profile with code 'Error'.`, but is very cryptic.

Any help?

*Edit*: I should mention I'm on Windows 10 with an RX560 and up-to-date drivers.

**Comment by bpurnomo** [comment]
Hi.  This is expected currently as for RDP to capture an RGP profile from the running application, the driver requires the presence of vkQueuePresentKHR API call to delimit the frames.  This is the RDP error that you see since your application does not contain the vkQueuePresentKHR API calls.  As a temporary workaround, could you add vkQueuePresentKHR API calls into your application?

**Comment by romanlarionov** [comment]
Hey, sorry for the delay. I needed to context switch for a while. I tried adding a dummy surface and present to it with vkQueuePresentKHR and it ended up working fine.

One thing I can suggest is that you add this requirement somewhere in the docs/readme. It was a bit frustrating when I was initially working on this.
