### ISSUE TITLE
Unable to capture profile

### ISSUE THREAD

**Issue by igpooh** [GPUOpen-Tools/Radeon-GPUProfiler#16]
I am trying to collect performance data. I attempted to capture twice but got the error 'NotReady'.
Cards I used are (with latest drivers 18.Q3.1): 
Radeon Pro WX7100 and RX580. Windows 10.
Could you please provide assistance to me?

There is my connection log:

[RDP] Loaded RDP settings file.
[RDP] Attempting to start Radeon Developer Service locally.
[RDP] Launching local RDS.
[RDP] Established connection to RDS within timeout.
[RDP] Connected successfully
[RDP] Received client connected from unknown client with id 2730.
[RDP] Received client halted from unknown client with id 2730.
[RDP] Processing halted client with id 2730: PerformanceBenchmark.exe:3304 - AMD Vulkan Driver
[RDP] Updated PerformanceBenchmark.exe ClientId to 2730
[RDP] Connected DriverControlClient to process 'PerformanceBenchmark.exe', ProcessId = 3304
[RDP] Filtered halted process with ProcessId = 3304
[RDP] EnableProfiling() for clientId 2730.
[RDP] Enabled profiling for target executable 'PerformanceBenchmark.exe', ProcessId = 3304.
[RDP] Can enable profiling for client ID 2730
[RDP] Set profiling flag for ProcessId = 3304 (client ID 2730) to true.
[RDP] Capture profile button is enabled because the target application is profilable and there is no profile in progress.
[RDP] Found 0 settings.
[RDP] Resumed execution of process 'PerformanceBenchmark.exe', ProcessId = 3304. Disconnect client.
[RDP] Driver has been initialized within PerformanceBenchmark.exe process. Attempting to retrieve device clock frequencies.
[RDP] Successfully queried maximum device clocks.
[RDP] Successfully set device clock mode to Normal to query frequency.
[RDP] Successfully queried device clock frequencies for Normal mode.
[RDP] Successfully set device clock mode to Stable to query frequency.
[RDP] Successfully queried device clock frequencies for Stable mode.
[RDP] Successfully collected device clock frequencies.
[RDP] Reverting to user's clock mode.
[RDP] Set clock mode to Normal.
[RDP] Driver initialized successfully on target client PerformanceBenchmark.exe.
[RDP] Capture profile button has been disabled because there is an active profile in progress.
[RDP] Set clock mode to Peak for profiling.
[RDP] Profiling began successfully.
[RDP] Reverted clock after profiling to Normal.
[RDP] Failed to finish executing profile with code 'NotReady'.
[RDP] Capture profile button is enabled because the target application is profilable and there is no profile in progress.
[RDP] Capture profile button has been disabled because there is an active profile in progress.
[RDP] Set clock mode to Peak for profiling.
[RDP] Profiling began successfully.
[RDP] Reverted clock after profiling to Normal.
[RDP] Failed to finish executing profile with code 'NotReady'.
[RDP] Client with Id 2730 has disconnected.

**Comment by ahosier** [comment]
Hi,

Thank you for your feedback. Do you have both cards in the machine at the same time? RGP doesn't support multi-GPU setups. With the RX-580, try capturing using the public Adrenaline Edition 18.10.1 driver here: https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-580

We'll take a look at the workstation card and driver and get back to you.

Thanks,
Tony.

**Comment by igpooh** [comment]
No, there are 2 single card workstations. I will try to update the driver.

**Comment by gselley** [comment]
Hi, I have tested using the configurations below, and am able to generate RGP profiles without an issue. From your log it looks like the application may not be rendering. Does your application stop rendering if its window loses focus? Does you app have a continuous rendering loop?

- Radeon Pro WX3100 and WX8200
- win10-64bit-radeon-pro-software-enterprise-18.q3.1-oct1.exe
- Bloom.exe and D3D12Multithreading.exe

- Radeon RX 580
- radeon-software-adrenalin-18.10.1-minimalsetup-181015_64bit
- Tested with DX12/VK SDK samples and titles

**Comment by igpooh** [comment]
I will check the ability to collect profile on VK SDK samples. My application is pure GPGPU kernels based on VK, so there is no rendering loop but I thought it was not really neccessary...

**Comment by bpurnomo** [comment]
Hi, your error is expected as RDP requires frame based application based on the presence of the vkQueuePresentKHR API call. This is used to define the start and end of the region being profiled. As a temporary workaround, could you add vkQueuePresentKHR API calls into your application?
