### ISSUE TITLE
Unable to capture profiler data on ubuntu 18.04 + Wx5100

### ISSUE THREAD

**Issue by tonyplee** [GPUOpen-Tools/Radeon-GPUProfiler#17]
System: Ubuntu 18.04
GPU: wx5100
AMDPro driver :  amdgpu-pro-18.20-621984

I can't capture any data with my own app. 
For testing, I try capture the data for /usr/bin/glxgears.   This also failed. 

Any suggestion on how to debug this issue?

--- Here's the connection log --- 
[RDP] Loaded RDP settings file.
[RDP] Attempting to start Radeon Developer Service locally.
[RDP] Launching local RDS.
[RDP] Established connection to RDS within timeout.
[RDP] Connected successfully

**Comment by cal3d** [comment]
RGP only supports the Vulkan API on Linux. There is no support for OpenGL.
