### ISSUE TITLE
VK_EXT_debug_utils support.

### ISSUE THREAD

**Issue by kennyalive** [GPUOpen-Tools/Radeon-GPUProfiler#18]
Is there support for debug markers created with VK_EXT_debug_utils extension? If no, it would be great to have this functionality. It is recommended extension for debug reporting/markers and probably more and more developers are starting to use it.

**Comment by bpurnomo** [comment]
Yes, the vulkan debug markers are supported by RGP.  See https://radeon-gpuprofiler.readthedocs.io/en/latest/#vulkan-user-markers.

**Comment by kennyalive** [comment]
Thanks a lot!

**Comment by bpurnomo** [comment]
vk_debug_utils is supported with the latest Vulkan driver.  Please open another issue if it doesn't work.
