### ISSUE TITLE
Incorrect primitive count

### ISSUE THREAD

**Issue by mhogdahl** [GPUOpen-Tools/Radeon-GPUProfiler#2]
Hi,

The primitive count, index count (Input Assembler tab) and Input primitives (Event timing tab) are computed from only the last draw of vkCmdDrawIndexedIndirect commands.

As a side effect the vertices/primitive stats will occasionally show something a few orders of magnitudes larger than 3 for triangles. That doesn't seem right to me. ;)

This tools is looking really good so far!

**Comment by ahosier** [comment]
Hi,

Thanks for the feedback. Do you have a profile file you can share with us? Thanks!

**Comment by mhogdahl** [comment]
Here you go.

You'll find these kinds of draws in event 90-126 and 165-271.

[XTest_XR_Vk-20170728-113716.zip](https://github.com/GPUOpen-Tools/Radeon-GPUProfiler/files/1182634/XTest_XR_Vk-20170728-113716.zip)

**Comment by ahosier** [comment]
Hi,
Thanks for providing the profile. We'll investigate the issue and hopefully have a fix soon.

**Comment by ahosier** [comment]
Hi,
This is now fixed in the latest release of RGP (V1.10). Please let us know if you see any issues. Thanks!
