### ISSUE TITLE
Sync primitives are missing on frame summary page RGP 1.4 + 19.x drivers

### ISSUE THREAD

**Issue by kennyalive** [GPUOpen-Tools/Radeon-GPUProfiler#20]
It seems RGP 1.4 does not work correctly with the latest drivers (19.x). On frame summary page I can't see sync primitives (those red and green bars). Corresponding option 'Sync objects' is disabled in UI and I can't turn it on. It worked with 18.x.

**Comment by kennyalive** [comment]
Another thing that could cause the above mentioned behavior is that I updated windows.

**Comment by bpurnomo** [comment]
I think you may be hitting known no 17.

**Comment by kennyalive** [comment]
This one https://github.com/GPUOpen-Tools/Radeon-GPUProfiler/issues/17 ?
If yes, than it looks like I have another problem since I'm on windows and running vulkan app. RGP worked correctly with the same app until I installed the latest AMD drivers + windows 10 update. So it's hard to say which change caused the issue but I think it should be relatively easy to check if it can be reproduced.

**Comment by bpurnomo** [comment]
No.
See item no 17 in https://github.com/GPUOpen-Tools/Radeon-GPUProfiler/blob/master/Known_Issues.md

**Comment by kennyalive** [comment]
Yes, that's it.

**Comment by bpurnomo** [comment]
Please out the latest Adrenalin 19.1.2 whether that has addressed your issue.

**Comment by kennyalive** [comment]
I'll check on Monday.

**Comment by kennyalive** [comment]
It works with 19.1.2.
