### ISSUE TITLE
Can't capture OpenCL with AMD Radeon VII on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by erdalpekel** [GPUOpen-Tools/Radeon-GPUProfiler#22]
Hello,

I'm using the Radeon GPU Profiler on Ubuntu 18.04.1 with the new AMD Radeon Vega VII card but can't use the capturing functionality.
I'm using the 18.50 drivers from the release day (February 7th, 2019)
I'm trying to profile OpenCL application but when I run the applications I can't click 'capture' in the 'Profiling section.

Is the Radeon VII even supported with OpenCL applications?
I'm running the GPU Profiler version 1.4.0.16

Thanks

**Comment by ahosier** [comment]
Hi,

OpenCL is supported on Ubuntu 18.04 on Radeon VII with the current public 18.50.725072 driver. A couple of things you could try:
(1) When installing the driver, be sure to use the --opencl=pal,legacy command line option for ./amdgpu-pro-install
(2) Try using the latest version of the Radeon GPU Profiler on the github page (1.4.0.30).
(3) It's possible that your application has completed before the RadeonDeveloperPanel has had a chance to connect with it. As a test, try downloading the luxmark benchmark (http://www.luxmark.info/). Start up the RadeonDeveloperPanel and click "Connect". Start the ./luxmark application and the panel should allow you to capture. 

Please get in touch if you're still seeing issues and we can investigate further.

Thanks,
Tony.

**Comment by scottkosty** [comment]
@erdalpekel just curious, did you make any progress on this?

**Comment by erdalpekel** [comment]
@scottkosty No I didn't try to use it since then.

**Comment by scottkosty** [comment]
@erdalpekel OK, thanks for the reply.

**Comment by bpurnomo** [comment]
Please make sure clinfo is reporting correct one GPU device for your system.  Otherwise, you would need to make sure to cleanly install the driver.
