### ISSUE TITLE
Ative applications doesn't show anything on Windows 10

### ISSUE THREAD

**Issue by razor85** [GPUOpen-Tools/Radeon-GPUProfiler#23]
Windows 10 Build 1809 here, with AMD Radeon RX580 and 19.4.1 Drivers. 

Opened Radeon Developer Panel 1.4.1.34, configured target application (tried multiple OpenCL applications) but none show on Active applications panel. Would be cool if we could just input process id.

**Comment by ahosier** [comment]
Hi razor85,

We just released RGP V1.5.1. This has a much simpler UI for capturing applications and should automatically latch on to the first application it finds.

Thanks,
Tony.

**Comment by bpurnomo** [comment]
Please reopen if there is still an issue with the latest version.

**Comment by razor85** [comment]
Still behave in the exact same way in the new build and with 19.6.2 drivers. Vulkan applications are detected but OpenCL aren't.
