### ISSUE TITLE
Profiler instantly shuts down without error message on certain compute shader traces

### ISSUE THREAD

**Issue by SaschaWillems** [GPUOpen-Tools/Radeon-GPUProfiler#3]
While testing the new profiler with my some of my examples I noticed that certain compute shader traces will cause the profiler to instantly close itself upon loading without any error or message whatsoever.

While the R9 390X isn't mentioned in the readme, other examples (including some compute ones) work fine, so I guess this may be caused by a certain combination triggered by those examples.

Here are a few traces that instantly crash/close the profiler for me:

[computecloth-20170727-213058.zip](https://github.com/GPUOpen-Tools/Radeon-GPUProfiler/files/1181062/computecloth-20170727-213058.zip)
[computenbody-20170727-213447.zip](https://github.com/GPUOpen-Tools/Radeon-GPUProfiler/files/1181063/computenbody-20170727-213447.zip)

**Comment by ahosier** [comment]
Hi,

Thanks for the feedback. We should have a fix for this in the very near future,

**Comment by gselley** [comment]
We just posted a new release with a fix for this issue. We are now able to load the traces you provided. Please note that it looks like you are using an R9 390 (GCN 2) which RGP does not support. The profiles have incomplete data and will not be usable. RGP only supports GCN 3 currently.

**Comment by SaschaWillems** [comment]
I can confirm that the new release works fine (even on a R9 390) and I can load the and profile the traces noted above.

Thx for the quick update!

**Comment by ahosier** [comment]
The traces may load but they contain incomplete data. I have attached a profile of computenbody taken on a Polaris. In particular, you'll notice that the system activity in the attached trace is populated. Also in the event timing pane, you'll see that the vkDmdDraw() events used to render the text contain timing values which are not 0 clocks.

[computenbody-20170727-160028.zip](https://github.com/GPUOpen-Tools/Radeon-GPUProfiler/files/1183501/computenbody-20170727-160028.zip)
