### ISSUE TITLE
Radeon 290 Support

### ISSUE THREAD

**Issue by Carandiru0** [GPUOpen-Tools/Radeon-GPUProfiler#31]
I was hoping I could ask for Radeon 290 (Hawaii) support. I see the Radeon 285 is supported - so I was hoping that adding support for the Radeon 290 would be a relatively small extension.
I'm using Vulkan 1.1 and there are simply no good profilers out there that support the Radeon 290 correctly. If I find a good deal on a Vega in Kijiji and had the money I would simply upgrade - however this is not the case.

Thanks !

**Comment by chesik-amd** [comment]
Unfortunately, adding Hawaii support is non-trivial.  We have no plans to support hardware older than what is currently supported.
