### ISSUE TITLE
DMA queue in Vulkan does not show anything

### ISSUE THREAD

**Issue by Themaister** [GPUOpen-Tools/Radeon-GPUProfiler#6]
On RX470 on Windows, submitting work to DMA queue (queue family 2), nothing shows up in the profiler. Async compute shows up however ... Windows 10 64-bit, latest drivers.

**Comment by Jasper-Bekkers** [comment]
Same happens on Fury X.

**Comment by ahosier** [comment]
HI,

Thanks for the feedback. Could you provide us with a profile so we could investigate further? Thanks!

**Comment by ahosier** [comment]
Hi,

We have root-caused the issue and should have a fix sometime in the near future. Thanks again for the feedback.

**Comment by ahosier** [comment]
The latest driver will allow you to see the DMA queues.
Linux: http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx
Windows: http://support.amd.com/en-us/download/desktop?os=Windows%2010%20-%2064
