### ISSUE TITLE
RGP fails to load particular capture on Linux.

### ISSUE THREAD

**Issue by Themaister** [GPUOpen-Tools/Radeon-GPUProfiler#9]
RGP: 1.11.20
PAL: Git from 2018-02-18

Capture:
https://drive.google.com/open?id=1YiRcxCN_u_9CTDo_e-RSiCvkAPZdYM3j

I get an error when trying to load the capture on Linux in Radeon Graphics Profiler:
```
No events detected:
There are no events in the loaded profile so there is nothing to optimize.
```

Taking a capture on Windows does work, however.

**Comment by gselley** [comment]
Thanks for the report, we are looking at the profile and will get back to you.

**Comment by perhaad** [comment]
Hi @Themaister, 
We took a look at the profile you provided and it seems the data in the RGP file is invalid. Can you point us to the test app you used to generate this profile ?

**Comment by bpurnomo** [comment]
If this is still an issue, please share the test app with us.
